name: FGO Login System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 07,19 * * *"
    - cron: "15 08,20 * * *"
    - cron: "15 12,00 * * *"
    - cron: "15 01,13 * * *"
    - cron: "15 02,14 * * *"
    - cron: "15 06,18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run main.py
        run: python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Run main02.py
        run: python3 main02.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
